const actionTypes = {
  GET_NEWS_DATA_SUCCESS: "GET_NEWS_DATA_SUCCESS",
  GET_NEWS_DATA_ERROR: "GET_NEWS_DATA_ERROR",
  GET_NEWS_DATA_START: " GET_NEWS_DATA_START",
  FETCH_DATA_START: "FETCH_DATA_START",
  GET_RANDOM_WORD_MEANING_START: "GET_RANDOM_WORD_MEANING_START",
  GET_RANDOM_WORD_MEANING_SUCCESS: "GET_RANDOM_WORD_MEANING_SUCCESS",
  GET_RANDOM_WORD_MEANING_ERROR: "GET_RANDOM_WORD_MEANING_ERROR",
  GET_SEARCH_WORD_SUCCESS: "GET_SEARCH_WORD_SUCCESS",
  GET_SEARCH_WORD_START: "GET_SEARCH_WORD_START",
  GET_SEARCH_WORD_ERROR: "GET_SEARCH_WORD_ERROR",
  SEARCHED_SUBJECT: "SEARCHED_SUBJECT",
  GET_QUESTION_QUIZ_SUCCESS: "GET_QUESTION_QUIZ_SUCCESS",
  GET_QUESTION_QUIZ_ERROR: "GET_QUESTION_QUIZ_ERROR",
  SEND_PERFORMANCE_DATA: "SEND_PERFORMANCE_DATA",
  CORRECT_ANSWERS: "CORRECT_ANSWERS",
};

export default actionTypes;
